name: Publish Pages

on:
  push:
    branches:
      - master

jobs:
  publish-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - run: build:site
      - name: Publish Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: site-build
          branch: gh-pages
